name: Deploy Manual

on:
  workflow_dispatch:

  push:
    branches: ["main"]
    paths: ["manual/**"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x

      - name: Install Dependencies
        working-directory: manual
        run: npm install

      - name: Build
        working-directory: manual
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: manual/dist

  deploy:
    name: Deploy

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
